"""
Financial Data Models — Pydantic models for the Financial Governance & Strategic Intelligence feature.
"""
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime
import uuid


# ---------------------------------------------------------------------------
# Core financial models
# ---------------------------------------------------------------------------

class FinancialTarget(BaseModel):
    """A financial target set by the user for a period."""
    id: Optional[str] = None
    revenue_target: float
    cost_budget: float
    margin_target: Optional[float] = None  # percentage 0-100
    period: str  # monthly | quarterly | annual
    period_start: str  # YYYY-MM-DD — start of the period
    program_id: Optional[str] = None  # None = portfolio-level
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class FinancialActual(BaseModel):
    """Recorded financial actuals for a period."""
    id: Optional[str] = None
    actual_revenue: float
    actual_cost: float
    actual_margin: Optional[float] = None  # auto-calculated if not provided
    period: str  # monthly | quarterly | annual
    period_start: str  # YYYY-MM-DD
    program_id: Optional[str] = None
    recorded_date: Optional[str] = None
    notes: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class ResourceCost(BaseModel):
    """A resource cost entry for a program."""
    id: Optional[str] = None
    resource_name: str
    cost_amount: float
    cost_type: str  # labour | tools | infrastructure | external
    program_id: str
    period: str  # monthly | quarterly | annual
    period_start: str  # YYYY-MM-DD
    billable_hours: Optional[float] = None
    notes: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


class ProgramFinancialProfile(BaseModel):
    """Financial profile metadata for a program."""
    program_id: str
    contribution_type: str = "direct_revenue"  # direct_revenue | indirect_revenue_impact
    revenue_streams: List[str] = []
    cost_centres: List[str] = []
    impact_attribution_pct: Optional[float] = None  # 0-100 for indirect programs
    notes: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


# ---------------------------------------------------------------------------
# Forecast models
# ---------------------------------------------------------------------------

class ForecastResult(BaseModel):
    """A financial forecast generated by the engine."""
    id: Optional[str] = None
    program_id: Optional[str] = None
    metric: str  # revenue | cost | margin
    horizon_months: int  # 3, 6, or 12
    projected_value: float
    confidence_lower_68: Optional[float] = None
    confidence_upper_68: Optional[float] = None
    confidence_lower_95: Optional[float] = None
    confidence_upper_95: Optional[float] = None
    on_track: bool = True
    variance_pct: Optional[float] = None
    generated_at: Optional[str] = None

    # Time series data points for charting
    forecast_points: List[Dict[str, Any]] = []  # [{date, value, lower, upper}]


class TrajectoryAnalysis(BaseModel):
    """Result of comparing actuals trajectory against targets."""
    program_id: Optional[str] = None
    metric: str  # revenue | cost | margin
    on_track: bool = True
    variance_pct: float = 0.0
    variance_absolute: float = 0.0
    run_rate: Optional[float] = None  # monthly rate from actuals
    projected_end_value: Optional[float] = None
    target_value: Optional[float] = None
    data_points: int = 0


# ---------------------------------------------------------------------------
# Risk models
# ---------------------------------------------------------------------------

class FinancialRisk(BaseModel):
    """A financial risk auto-generated or manually created."""
    risk_id: str
    description: str
    risk_type: str  # budget_overrun | revenue_shortfall | margin_erosion | resource_utilisation
    severity: str  # critical | high | medium | low
    probability: str  # high | medium | low
    impact: Optional[str] = None
    mitigation: Optional[str] = None
    status: str = "OPEN"  # OPEN | MITIGATED | CLOSED
    program_id: Optional[str] = None
    trigger_metric: Optional[str] = None  # which metric triggered this risk
    trigger_variance_pct: Optional[float] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


# ---------------------------------------------------------------------------
# Strategic lever models
# ---------------------------------------------------------------------------

class StrategicLever(BaseModel):
    """An AI-recommended strategic action to improve financial trajectory."""
    id: Optional[str] = None
    title: str
    description: str
    lever_type: str  # cost_reduction | revenue_acceleration | resource_reallocation | risk_mitigation
    estimated_impact: float  # estimated financial impact amount
    confidence: float = 0.5  # 0-1 confidence in the recommendation
    effort_level: str = "medium"  # low | medium | high
    affected_programs: List[str] = []
    recommended_timeline: Optional[str] = None
    status: str = "proposed"  # proposed | accepted | rejected | implemented
    generated_at: Optional[str] = None


# ---------------------------------------------------------------------------
# Attribution models
# ---------------------------------------------------------------------------

class ImpactAttribution(BaseModel):
    """Impact attribution for an indirect-revenue program."""
    program_id: str
    program_name: Optional[str] = None
    attribution_pct: float  # 0-100
    confidence_score: Optional[float] = None  # 0-1, data-backed confidence
    set_by: str = "manual"  # manual | engine
    effective_date: Optional[str] = None
    notes: Optional[str] = None


class AttributionHistory(BaseModel):
    """Historical record of attribution changes."""
    program_id: str
    entries: List[ImpactAttribution] = []


# ---------------------------------------------------------------------------
# Request / Response models for the API
# ---------------------------------------------------------------------------

class FinancialTargetRequest(BaseModel):
    """API request model for creating/updating financial targets."""
    revenue_target: float
    cost_budget: float
    margin_target: Optional[float] = None
    period: str  # monthly | quarterly | annual
    period_start: str  # YYYY-MM-DD
    program_id: Optional[str] = None


class FinancialActualRequest(BaseModel):
    """API request model for recording financial actuals."""
    actual_revenue: float
    actual_cost: float
    period: str
    period_start: str  # YYYY-MM-DD
    program_id: Optional[str] = None
    notes: Optional[str] = None


class ResourceCostRequest(BaseModel):
    """API request model for recording resource costs."""
    resource_name: str
    cost_amount: float
    cost_type: str  # labour | tools | infrastructure | external
    program_id: str
    period: str
    period_start: str  # YYYY-MM-DD
    billable_hours: Optional[float] = None
    notes: Optional[str] = None


class AttributionRequest(BaseModel):
    """API request model for setting impact attribution."""
    program_id: str
    attribution_pct: float  # 0-100
    notes: Optional[str] = None


class ProgramProfileRequest(BaseModel):
    """API request model for setting program financial profile."""
    program_id: str
    contribution_type: str = "direct_revenue"
    revenue_streams: List[str] = []
    cost_centres: List[str] = []
    notes: Optional[str] = None


class FinancialImportRequest(BaseModel):
    """Response model for bulk import results."""
    total_rows: int = 0
    imported: int = 0
    errors: List[Dict[str, Any]] = []


# ---------------------------------------------------------------------------
# Dashboard summary models
# ---------------------------------------------------------------------------

class FinancialSummary(BaseModel):
    """Aggregated financial summary for dashboard KPIs."""
    total_revenue_target: float = 0.0
    total_revenue_actual: float = 0.0
    total_cost_budget: float = 0.0
    total_cost_actual: float = 0.0
    target_margin: Optional[float] = None
    actual_margin: Optional[float] = None
    revenue_variance_pct: float = 0.0
    cost_variance_pct: float = 0.0
    forecast_accuracy: Optional[float] = None
    resource_utilisation: Optional[float] = None
    financial_risk_score: Optional[float] = None
    on_track: bool = True
    program_count: int = 0

    # Per-program breakdowns
    program_summaries: List[Dict[str, Any]] = []


# Fields that require encryption
ENCRYPTED_FIELDS = ["notes", "resource_name"]

# Valid values for enums
VALID_PERIODS = {"monthly", "quarterly", "annual"}
VALID_COST_TYPES = {"labour", "tools", "infrastructure", "external"}
VALID_CONTRIBUTION_TYPES = {"direct_revenue", "indirect_revenue_impact"}
VALID_RISK_TYPES = {"budget_overrun", "revenue_shortfall", "margin_erosion", "resource_utilisation"}
VALID_LEVER_TYPES = {"cost_reduction", "revenue_acceleration", "resource_reallocation", "risk_mitigation"}
